# Generated by Django 3.0.2 on 2020-02-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='article_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='article_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='article_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='article_5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='article_6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='article_7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='article_8',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='article_9',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='image_1',
            field=models.ImageField(default='', upload_to='../media/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_2',
            field=models.ImageField(default='', upload_to='../media/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_3',
            field=models.ImageField(default='', upload_to='../media/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_4',
            field=models.ImageField(default='', upload_to='../media/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_5',
            field=models.ImageField(default='', upload_to='../media/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_6',
            field=models.ImageField(default='', upload_to='../media/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_7',
            field=models.ImageField(default='', upload_to='../media/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_8',
            field=models.ImageField(default='', upload_to='../media/'),
        ),
        migrations.AddField(
            model_name='article',
            name='image_9',
            field=models.ImageField(default='', upload_to='../media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='../media/'),
        ),
    ]
