# Generated by Django 3.0.2 on 2020-02-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeration', '0003_auto_20200213_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_8',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_9',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_1',
            field=models.ImageField(blank=True, default='', upload_to='../media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_2',
            field=models.ImageField(blank=True, default='', upload_to='../media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_3',
            field=models.ImageField(blank=True, default='', upload_to='../media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_4',
            field=models.ImageField(blank=True, default='', upload_to='../media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_5',
            field=models.ImageField(blank=True, default='', upload_to='../media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_6',
            field=models.ImageField(blank=True, default='', upload_to='../media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_7',
            field=models.ImageField(blank=True, default='', upload_to='../media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_8',
            field=models.ImageField(blank=True, default='', upload_to='../media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_9',
            field=models.ImageField(blank=True, default='', upload_to='../media/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True),
        ),
    ]
